### ISSUE TITLE
`if` on `Option`s creates unsolvable VCs

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#255]
This may very well apply to more types than `Option`. VCs might actually be solvable, I just couldn't figure out a way.

Related to issue #163 

Example:
```rust
extern crate creusot_contracts;
use creusot_contracts::std::*;
use creusot_contracts::*;

fn unsolvable(a: &Vec<Option<i32>>) {
    let mut i: usize = 0;
    while i < a.len() {
        let none = None; // To circumvent issue #163
        if a[i] == none { }
        i += 1;
    }
}

fn unsolvable2(a: &Vec<Option<bool>>) {
    let mut i: usize = 0;
    while i < a.len() {
        let some_true = Some(true); // To circumvent issue #163
        if a[i] == some_true { }
        i += 1;
    }
}

fn ok(a: &Vec<Option<bool>>) {
    let mut i: usize = 0;
    while i < a.len() {
        match a[i] {
            Some(true) => {}
            Some(false) => {}
            None => {}
        }
        i += 1;
    }
}
```
The function named `ok` passes just fine, whereas the first two generate a precondition with the Goal: "goal unsolveable'vc : false"

Should probably either be fixed or made to error similar to how:
```rust
fn errors(a: &Vec<Option<bool>>) {
    let mut i: usize = 0;
    while i < a.len() {
        let res = a[i]; // To circumvent issue #163
        if res == None { }
        i += 1;
    }
}
```
errors.

I tried to see if it applied to alternative ways to represent `Option(bool)`:

This implementation:
```rust
enum M {
    None,
    B(bool),
}

impl PartialEq for M {
    fn eq(&self, other: &Self) -> bool {
        return match (self, other) {
            (M::None,  M::None) => true,
            (M::B(a),  M::B(b)) => a == b,
            _ => false,
        };
    }
}
```
Gives "thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', creusot/src/translation/function.rs:362:18", but that might be me doing something wrong.

The following seems to be working fine:
```rust
#[derive(Copy)]
enum OptionBool {
    True,
    False,
    None,
}

impl PartialEq for OptionBool {
    fn eq(&self, other: &Self) -> bool {
        return match (self, other) {
            (OptionBool::None,  OptionBool::None) => true,
            (OptionBool::True,  OptionBool::True) => true,
            (OptionBool::False, OptionBool::False) => true,
            _ => false,
        };
    }
}

fn ok2(a: &Vec<OptionBool>) {
    let mut i: usize = 0;
    while i < a.len() {
        let none = OptionBool::None; // To circumvent issue #163
        if a[i] == none { }
        i += 1;
    }
}
```
As does a regular vector of `bool`s.

Somewhat related, double borrows creates unsolvable VCs as well:
```rust
enum N {
    None,
}

impl PartialEq for N {
    fn eq(&self, other: &Self) -> bool {
        return match (self, other) {
            (N::None,  N::None) => true,
            _ => false,
        };
    }
}

fn unsolvable_double_borrow(a: &Vec<N>) {
    let mut i: usize = 0;
    while i < a.len() {
        let res = &a[i];
        let none = N::None; // To circumvent issue #163
        if res == &none { }
        i += 1;
    }
}

fn solveable3(a: &Vec<N>) {
    let mut i: usize = 0;
    while i < a.len() {
        let none = N::None; // To circumvent issue #163
        if a[i] == none { }
        i += 1;
    }
}
```

**Comment by xldenis** [comment]
The 'unsolveable' vcs you are seeing are because you are calling an external function (the implementation of `eq` for `Option` or `&mut T where T : PartialEq`) which has no contract.
When we call an external function which hasn't been given a contract using the upcoming #254, we _must_ give it the precondition `false` as we don't know what it could do: panic? diverge? etc...

However along the way it seems like you also stumbled on a panic in Creusot. 

> Gives "thread 'rustc' panicked at 'called Option::unwrap() on a None value', creusot/src/translation/function.rs:362:18", but that might be me doing something wrong.

which should be fixed.
