### ISSUE TITLE
Unreachable patterns causes Creusot to panic

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#271]
Examples:
```rust
fn ex() {
    let a = 0;
    match a {
        _ => {}
        0 => {}
    }
}
fn ex2() {
    let a = 0;
    match a {
        0 | 1 => {}
        1 => {}
    }
}
fn ex3() {
    let a = 0;
    match a {
        0 | 1 => {}
        1 | 2 => {}
    }
}
```
Cause the following error:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_data_structures/src/graph/dominators/mod.rs:138:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new
```

**Comment by sarsko** [comment]
> Fascinating, I wonder why, are you sure it's not an issue with literal patterns instead?

Might very well be. These do not error:
```rust
fn no_err() {
    let a = 0;
    match a {
        0..=8 => {},
        0..=9 => {}
    }
}
fn no_err2() {
    let a = 0;
    match a {
        0..=8 => {},
        0..=7 => {}
    }
}
```
Whereas this one does:
```rust
fn err() {
    let a = 0;
    match a {
        0..=8 => {},
        0..=8 => {}
    }
}
```

**Comment by xldenis** [comment]
Could you get a stacktrace for the failing example?

**Comment by sarsko** [comment]
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_data_structures/src/graph/dominators/mod.rs:138:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/library/core/src/panicking.rs:110:14
   2: core::panicking::panic
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/library/core/src/option.rs:729:21
   4: rustc_data_structures::graph::dominators::dominators
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_data_structures/src/graph/dominators/mod.rs:138:21
   5: rustc_middle::mir::Body::dominators
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_middle/src/mir/mod.rs:527:9
   6: creusot::resolve::EagerResolver::unactivated_borrows
             at ./creusot/src/resolve.rs:55:19
   7: creusot::resolve::EagerResolver::locals_resolved_between
             at ./creusot/src/resolve.rs:127:30
   8: creusot::resolve::EagerResolver::locals_resolved_at_loc
             at ./creusot/src/resolve.rs:89:9
   9: creusot::translation::function::FunctionTranslator::freeze_borrows_dying_at
             at ./creusot/src/translation/function.rs:379:21
  10: creusot::translation::function::FunctionTranslator::translate_body
             at ./creusot/src/translation/function.rs:235:17
  11: creusot::translation::function::FunctionTranslator::translate
             at ./creusot/src/translation/function.rs:187:9
  12: creusot::translation::function::translate_function
             at ./creusot/src/translation/function.rs:66:5
  13: creusot::ctx::TranslationCtx::translate_function
             at ./creusot/src/ctx.rs:137:24
  14: creusot::ctx::TranslationCtx::translate
             at ./creusot/src/ctx.rs:72:17
  15: creusot::translation::translate
             at ./creusot/src/translation.rs:52:9
  16: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::{{closure}}
             at ./creusot/src/callbacks.rs:37:26
  17: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_interface/src/passes.rs:821:42
  18: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_middle/src/ty/context.rs:1764:50
  19: rustc_middle::ty::context::tls::set_tlv
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_middle/src/ty/context.rs:1748:9
  20: rustc_middle::ty::context::tls::enter_context
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_middle/src/ty/context.rs:1764:9
  21: rustc_interface::passes::QueryContext::enter
             at /rustc/ad46af24713115e7b9b258346e66b9b2d14eacfc/compiler/rustc_interface/src/passes.rs:821:9
  22: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
             at ./creusot/src/callbacks.rs:33:9
  23: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  24: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  25: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  26: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

**Comment by xldenis** [comment]
oh wow... that is _not_ the code i expected to be failing.

**Comment by xldenis** [comment]
PR #275 fixes the last two examples given since they are also non-exhaustive. I still don't understand what leads to the `dominator` calculation failing here.

**Comment by xldenis** [comment]
My guess is that the CFG is not actually a CFG because the unreachable block isn't connected after mir construction. Normally a pass like `SimplifyCFG` would clean this up but I can't call it from the API anymore :(.
