### ISSUE TITLE
Deriving `Debug` causes Creusot to 'violently' panic

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#296]
Forgetting to remove a `#[derive(Debug)]` as in:
```rust
#[derive(Debug)]
pub struct E { }
```
Will result in Creusot panicking without giving the user any indication of why.
Backtrace:
```
thread 'rustc' panicked at 'internal error: entered unreachable code', creusot/src/translation/ty.rs:123:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/panicking.rs:48:5
   3: creusot::translation::ty::translate_ty_inner
             at ./creusot/src/translation/ty.rs:123:14
   4: creusot::translation::ty::translate_ty_inner
             at ./creusot/src/translation/ty.rs:101:47
   5: creusot::translation::ty::field_ty
             at ./creusot/src/translation/ty.rs:271:5
   6: creusot::translation::ty::translate_tydecl::{{closure}}
             at ./creusot/src/translation/ty.rs:239:26
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:2203:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/adapters/map.rs:124:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:772:9
  11: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_extend.rs:40:17
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_from_iter.rs:33:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/mod.rs:2547:9
  15: core::iter::traits::iterator::Iterator::collect
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:1777:9
  16: creusot::translation::ty::translate_tydecl
             at ./creusot/src/translation/ty.rs:236:37
  17: creusot::translation::ty::translate_ty_name
             at ./creusot/src/translation/ty.rs:189:9
  18: creusot::translation::ty::translate_ty_inner
             at ./creusot/src/translation/ty.rs:77:35
  19: creusot::translation::ty::translate_ty_inner
             at ./creusot/src/translation/ty.rs:101:47
  20: creusot::translation::ty::translate_ty
             at ./creusot/src/translation/ty.rs:44:5
  21: creusot::util::signature_of::{{closure}}::{{closure}}
             at ./creusot/src/util.rs:270:51
  22: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::__iterator_get_unchecked
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/adapters/map.rs:134:18
  23: <core::iter::adapters::zip::Zip<A,B> as core::iter::adapters::zip::ZipImpl<A,B>>::next
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/adapters/zip.rs:278:59
  24: <core::iter::adapters::zip::Zip<A,B> as core::iter::traits::iterator::Iterator>::next
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/adapters/zip.rs:84:9
  25: core::iter::traits::iterator::Iterator::fold
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:2202:29
  26: core::iter::traits::iterator::Iterator::for_each
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:772:9
  27: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_extend.rs:40:17
  28: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  29: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/spec_from_iter.rs:33:9
  30: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/alloc/src/vec/mod.rs:2547:9
  31: core::iter::traits::iterator::Iterator::collect
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/iter/traits/iterator.rs:1777:9
  32: creusot::util::signature_of::{{closure}}
             at ./creusot/src/util.rs:260:13
  33: creusot::clone_map::CloneMap::with_public_clones
             at ./creusot/src/clone_map.rs:190:19
  34: creusot::util::signature_of
             at ./creusot/src/util.rs:258:9
  35: creusot::translation::interface::interface_for
             at ./creusot/src/translation/interface.rs:19:19
  36: creusot::ctx::TranslationCtx::translate_function
             at ./creusot/src/ctx.rs:118:33
  37: creusot::ctx::TranslationCtx::translate
             at ./creusot/src/ctx.rs:74:17
  38: creusot::translation::traits::<impl creusot::ctx::TranslationCtx>::translate_trait
             at ./creusot/src/translation/traits.rs:24:13
  39: creusot::translation::traits::<impl creusot::ctx::TranslationCtx>::translate_impl
             at ./creusot/src/translation/traits.rs:38:9
  40: creusot::ctx::TranslationCtx::translate
             at ./creusot/src/ctx.rs:72:31
  41: creusot::ctx::TranslationCtx::translate_function
             at ./creusot/src/ctx.rs:102:25
  42: creusot::ctx::TranslationCtx::translate
             at ./creusot/src/ctx.rs:74:17
  43: creusot::translation::translate
             at ./creusot/src/translation.rs:69:9
  44: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::{{closure}}
             at ./creusot/src/callbacks.rs:37:26
  45: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_interface/src/passes.rs:834:42
  46: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1776:50
  47: rustc_middle::ty::context::tls::set_tlv
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1760:9
  48: rustc_middle::ty::context::tls::enter_context
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1776:9
  49: rustc_interface::passes::QueryContext::enter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_interface/src/passes.rs:834:9
  50: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
             at ./creusot/src/callbacks.rs:33:9
  51: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  52: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

Tested for most of the other 'usual suspects' which may be derived. Those seem to work fine/give meaningful error messages if not.

**Comment by xldenis** [comment]
Yea oops, I accidentally removed the good error message while debugging stuff.
