### ISSUE TITLE
thread 'rustc' panicked at 'internal error: entered unreachable code'  when forgetting `()` when using predicates

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#310]
Impressed it has taken me this long to do this mistake
```rust
#[predicate]
pub fn ex() -> bool { true }

pub fn main() {
    proof_assert!(ex);
}
```
gives:
```rust
thread 'rustc' panicked at 'internal error: entered unreachable code', creusot/src/translation/ty.rs:123:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new
```
(`ex` should be `ex()`)

The same applies if one attempts to call a `logic` function/does the same in an `ensures/requires/invariant` block

Full trace:
```rust
     Running `target/debug/creusot-rustc -Z --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib --cfg contracts -Ldependency=./target/debug/deps/ --crate-type=lib --out-dir ../. /home/sarek/master/sat-mirror/src/ex.rs`
thread 'rustc' panicked at 'internal error: entered unreachable code', creusot/src/translation/ty.rs:123:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/e646f3d2a9541952310778288854943678738ea9/library/core/src/panicking.rs:48:5
   3: creusot::translation::ty::translate_ty_inner
             at ./creusot/src/translation/ty.rs:123:14
   4: creusot::translation::ty::translate_ty
             at ./creusot/src/translation/ty.rs:44:5
   5: creusot::translation::constant::from_mir_constant_kind
             at ./creusot/src/translation/constant.rs:26:14
   6: creusot::translation::specification::lower::Lower::lower_term
             at ./creusot/src/translation/specification/lower.rs:43:35
   7: creusot::translation::specification::lower::lower_pure
             at ./creusot/src/translation/specification/lower.rs:16:20
   8: creusot::gather_spec_closures::GatherSpecClosures::gather
             at ./creusot/src/gather_spec_closures.rs:47:27
   9: creusot::translation::function::translate_function
             at ./creusot/src/translation/function.rs:54:18
  10: creusot::ctx::TranslationCtx::translate_function
             at ./creusot/src/ctx.rs:139:24
  11: creusot::ctx::TranslationCtx::translate
             at ./creusot/src/ctx.rs:74:17
  12: creusot::translation::translate
             at ./creusot/src/translation.rs:69:9
  13: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::{{closure}}
             at ./creusot/src/callbacks.rs:37:26
  14: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_interface/src/passes.rs:834:42
  15: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1776:50
  16: rustc_middle::ty::context::tls::set_tlv
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1760:9
  17: rustc_middle::ty::context::tls::enter_context
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_middle/src/ty/context.rs:1776:9
  18: rustc_interface::passes::QueryContext::enter
             at /rustc/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_interface/src/passes.rs:834:9
  19: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
             at ./creusot/src/callbacks.rs:33:9
  20: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  21: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

**Comment by xldenis** [comment]
I think this error is 'fixed' by virtue of reporting a 'decent' error message now saying that we don't support function pointer types.
