### ISSUE TITLE
`const` functions cause Creusot panic

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#358]
Making a function `const` and running Creusot causes the following stack trace:
```
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', creusot/src/translation/function.rs:61:25
stack backtrace:
   0:     0x7f764d49e94d - std::backtrace_rs::backtrace::libunwind::trace::h70202ab8ffbd5ac3
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f764d49e94d - std::backtrace_rs::backtrace::trace_unsynchronized::hcef867f7e4ec1062
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f764d49e94d - std::sys_common::backtrace::_print_fmt::hcdc2f302ecf134a1
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f764d49e94d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb30b401e57e79b1c
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f764d4f8fcc - core::fmt::write::h879b0ff27230a85f
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f764d490141 - std::io::Write::write_fmt::h8754a3bba816b052
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/io/mod.rs:1655:15
   6:     0x7f764d4a1665 - std::sys_common::backtrace::_print::h5e99c900ab47e98d
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f764d4a1665 - std::sys_common::backtrace::print::h0d3f61b06a50b94b
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f764d4a1665 - std::panicking::default_hook::{{closure}}::h0c6c4d3eae89fc1b
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/panicking.rs:295:22
   9:     0x7f764d4a12d9 - std::panicking::default_hook::h339194ad7da4935c
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/panicking.rs:314:9
  10:     0x5612fbcb93e4 - creusot_rustc::report_panic::h895e914890c50c59
  11:     0x7f763c375f83 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3cd9ef1bcde47440
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/alloc/src/boxed.rs:1880:9
  12:     0x7f763c3556dd - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h810efe41befe255c
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/proc_macro/src/bridge/client.rs:335:21
  13:     0x7f764d4a1e36 - std::panicking::rust_panic_with_hook::hf7f51ed363e187f1
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/panicking.rs:702:17
  14:     0x7f764d4a1c37 - std::panicking::begin_panic_handler::{{closure}}::hd1b1adbfc3715499
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/panicking.rs:588:13
  15:     0x7f764d49ee04 - std::sys_common::backtrace::__rust_end_short_backtrace::h67c37f050bf5dda7
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7f764d4a1969 - rust_begin_unwind
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/panicking.rs:584:5
  17:     0x7f764d465913 - core::panicking::panic_fmt::h1bdc0f93a45ee55b
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/core/src/panicking.rs:142:14
  18:     0x5612fbe134f9 - rustc_data_structures::steal::Steal<T>::borrow::hfa015411f2fc947d
  19:     0x5612fbe69252 - creusot::translation::function::translate_function::h9a4329d83f930404
  20:     0x5612fbda4202 - creusot::ctx::TranslationCtx::translate_function::haaebc1bb1b793544
  21:     0x5612fbda2b5c - creusot::ctx::TranslationCtx::translate::hdef8b2d207ca9210
  22:     0x5612fbd71c37 - creusot::translation::after_analysis::he52c33f603815b09
  23:     0x5612fbe12d9c - rustc_interface::passes::QueryContext::enter::h47778f7c3556f882
  24:     0x5612fbd8c642 - <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::h8899640ef52e2bfc
  25:     0x7f764fccb744 - <rustc_interface[d04cb700f64809ea]::interface::Compiler>::enter::<rustc_driver[3e913dff2e5f5761]::run_compiler::{closure#1}::{closure#2}, core[7c80df3c8c832684]::result::Result<core[7c80df3c8c832684]::option::Option<rustc_interface[d04cb700f64809ea]::queries::Linker>, rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>
  26:     0x7f764fcf441f - rustc_span[b4d593114847993c]::with_source_map::<core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>, rustc_interface[d04cb700f64809ea]::interface::create_compiler_and_run<core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>, rustc_driver[3e913dff2e5f5761]::run_compiler::{closure#1}>::{closure#1}>
  27:     0x7f764fccc437 - <scoped_tls[1052271cf5364663]::ScopedKey<rustc_span[b4d593114847993c]::SessionGlobals>>::set::<rustc_interface[d04cb700f64809ea]::interface::run_compiler<core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>, rustc_driver[3e913dff2e5f5761]::run_compiler::{closure#1}>::{closure#0}, core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>
  28:     0x7f764fce182f - std[5548d7f6ffa838a9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d04cb700f64809ea]::util::run_in_thread_pool_with_globals<rustc_interface[d04cb700f64809ea]::interface::run_compiler<core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>, rustc_driver[3e913dff2e5f5761]::run_compiler::{closure#1}>::{closure#0}, core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>::{closure#0}, core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>
  29:     0x7f764fce1979 - <<std[5548d7f6ffa838a9]::thread::Builder>::spawn_unchecked_<rustc_interface[d04cb700f64809ea]::util::run_in_thread_pool_with_globals<rustc_interface[d04cb700f64809ea]::interface::run_compiler<core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>, rustc_driver[3e913dff2e5f5761]::run_compiler::{closure#1}>::{closure#0}, core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>::{closure#0}, core[7c80df3c8c832684]::result::Result<(), rustc_errors[1e81c6c5d088af86]::ErrorGuaranteed>>::{closure#1} as core[7c80df3c8c832684]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f764d4ac013 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h65c74a49fda44fc2
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/alloc/src/boxed.rs:1866:9
  31:     0x7f764d4ac013 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16c7647d337965d6
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/alloc/src/boxed.rs:1866:9
  32:     0x7f764d4ac013 - std::sys::unix::thread::Thread::new::thread_start::h62f3f5f315117c47
                               at /rustc/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f764d2835c2 - start_thread
  34:     0x7f764d308584 - __clone
  35:                0x0 - <unknown>

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

**Comment by xldenis** [comment]
oh. fun.

**Comment by xldenis** [comment]
I think I have a potential solution to this and thus #616. In `before_analysis` we can request the `mir_promoted` for every `const fn` in the crate. We can put it in a side-table which we can read from later on.

**Comment by jhaye** [comment]
This appears to have fixed things for me. I can't reproduce the errors described in #616 any more.

**Comment by xldenis** [comment]
> This appears to have fixed things for me. I can't reproduce the errors described in https://github.com/xldenis/creusot/issues/616 any more.

Wait, what? I haven't performed this proposed change, is this something you did locally?

**Comment by jhaye** [comment]
I see, I thought the most recent changes included those fixes. Seems like these problems are a bit harder to reproduce than I thought. Sorry for the misunderstanding.
