### ISSUE TITLE
Resolve can't be used in contracts

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#44]
`ma.resolve()`, equivalent to `equal(*ma, ^ma)`, can't be used in contracts.

It emits the following stack backtrace. Probably the error is related to handling of type polymorphism?
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', creusot/src/clone_map.rs:220:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: creusot::clone_map::type_param_subst
             at ./creusot/src/clone_map.rs:220:18
   4: creusot::clone_map::clone_item
             at ./creusot/src/clone_map.rs:188:27
   5: creusot::clone_map::CloneMap::to_clones
             at ./creusot/src/clone_map.rs:170:24
   6: creusot::translation::function::FunctionTranslator::translate
             at ./creusot/src/translation/function.rs:170:22
   7: creusot::translation::function::translate_function
             at ./creusot/src/translation/function.rs:48:18
   8: creusot::ctx::TranslationCtx::translate_function
             at ./creusot/src/ctx.rs:76:17
   9: creusot::translation::translate
             at ./creusot/src/translation.rs:40:9
  10: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::{{closure}}
             at ./creusot/src/callbacks.rs:42:17
  11: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/compiler/rustc_interface/src/passes.rs:780:42
  12: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/compiler/rustc_middle/src/ty/context.rs:1784:50
  13: rustc_middle::ty::context::tls::set_tlv
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/compiler/rustc_middle/src/ty/context.rs:1768:9
  14: rustc_middle::ty::context::tls::enter_context
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/compiler/rustc_middle/src/ty/context.rs:1784:9
  15: rustc_interface::passes::QueryContext::enter
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/compiler/rustc_interface/src/passes.rs:780:9
  16: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
             at ./creusot/src/callbacks.rs:33:9
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: rustc_interface::interface::create_compiler_and_run
  20: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by xldenis** [comment]
I haven't really worked on this but I think it will be fixed as part of another fix I'm working on. The issue here was that we were resolving an impl for a trait in the logic but using the old substitution. So for example we had `resolve, [(u32, u32)]`, and we turned it into `resolve_impl_for_pair, [(u32, u32)]` when it should have been `resolve_impl_for_pair, [u32, u32]`.
