### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by frank-king** [xldenis/creusot#449]
I failed to run `./build`, and the error messages were:

```
    Finished test [unoptimized + debuginfo] target(s) in 0.23s
     Running unittests src/lib.rs (.cargo/target/debug/deps/creusot-1672fc29eab539f5)

running 1 test
test arg_value::test_arg_value ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/bin/cargo-creusot.rs (.cargo/target/debug/deps/cargo_creusot-7d031858e4829aca)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/bin/creusot-rustc.rs (.cargo/target/debug/deps/creusot_rustc-303834bf70aaa4c2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/ui.rs (.cargo/target/debug/deps/ui-baf049c509fec426)
   Compiling creusot-contracts v0.1.0 (github/xldenis/creusot/creusot-contracts)
warning: unused import: `creusot_contracts_proc::*`
 --> creusot-contracts/src/bigint.rs:4:5
  |
4 | use creusot_contracts_proc::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', creusot/src/metadata.rs:223:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/core/src/result.rs:1098:23
   4: creusot::metadata::dump_exports
             at ./creusot/src/metadata.rs:223:5
   5: creusot::translation::after_analysis
             at ./creusot/src/translation.rs:92:9
   6: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion::{{closure}}
             at ./creusot/src/callbacks.rs:40:21
   7: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/compiler/rustc_interface/src/passes.rs:819:42
   8: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/compiler/rustc_middle/src/ty/context.rs:1868:50
   9: rustc_middle::ty::context::tls::set_tlv
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/compiler/rustc_middle/src/ty/context.rs:1852:9
  10: rustc_middle::ty::context::tls::enter_context
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/compiler/rustc_middle/src/ty/context.rs:1868:9
  11: rustc_interface::passes::QueryContext::enter
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/compiler/rustc_interface/src/passes.rs:819:9
  12: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
             at ./creusot/src/callbacks.rs:35:17
  13: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  14: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  15: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
warning: `creusot-contracts` (lib) generated 1 warning
error: could not compile `creusot-contracts`; 1 warning emitted
error: test failed, to rerun pass '-p creusot --test ui'
```

**Comment by xldenis** [comment]
what operating system is this on?

**Comment by frank-king** [comment]
Ubuntu 22.04

**Comment by frank-king** [comment]
I reran it with `RUST_LOG=warn", there are some warnings

```
[2022-07-03T05:38:07Z WARN  creusot::metadata] could not read metadata for crate `"std"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2022-07-03T05:38:07Z WARN  creusot::metadata] could not read metadata for crate `"core"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2022-07-03T05:38:07Z WARN  creusot::metadata] could not read metadata for crate `"creusot_contracts_proc"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2022-07-03T05:38:07Z WARN  creusot::metadata] could not read metadata for crate `"num_bigint"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2022-07-03T05:38:07Z WARN  creusot::metadata] could not encode metadata for crate `"LOCAL_CRATE"`, error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Probably because of no access right?

**Comment by xldenis** [comment]
Yea, how did you install rust? Is it through `rustup`?

**Comment by frank-king** [comment]
Oh, it's because I set the `target-dir` to a big `$HOME/.cargo/target` directory. I removed this config and the tests passed.

I do have the read and write access of `$HOME/.cargo/target`, are there any path dependent parts in Creusot?

**Comment by xldenis** [comment]
> I do have the read and write access of $HOME/.cargo/target, are there any path dependent parts in Creusot?

There shouldn't be any no. I'll update the error message so it actually explains which path it's trying to write to.

**Comment by frank-king** [comment]
Unfortunately, the passed test might be false positive. It failed again if I run with `RUST_LOG=warn ./build` (But passed when I run `./build` instead).

```
Testing tests/should_succeed/100doors.rs ... failure
[2022-07-04T16:06:03Z WARN  creusot::metadata] could not read metadata for crate `"std"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Testing tests/should_succeed/all_zero.rs ... failure
[2022-07-04T16:06:04Z WARN  creusot::metadata] could not read metadata for crate `"std"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Testing tests/should_succeed/binary_search.rs ... failure
[2022-07-04T16:06:04Z WARN  creusot::metadata] could not read metadata for crate `"std"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by xldenis** [comment]
I'm sorry, I seem to have let this fall aside, did you end up solving this issue?

**Comment by frank-king** [comment]
Not really, but it's not blocking since removing the `build.target-dir` option in `$HOME/.cargo/config` could "fix" it.

**Comment by xldenis** [comment]
right, you had a shared target directory. I don't think Creusot will play nicely with that. I think I'm going to close this as won't fix then, sorry.
