### ISSUE TITLE
Creusot panics on unsupported branch in cloneable_name

### ISSUE THREAD

**Issue by jhaye** [xldenis/creusot#531]
To get familiar with Creusot, I tried using it on a student project of mine, but it panics with the following backtrace:

```
thread 'rustc' panicked at 'internal error: entered unreachable code', creusot/src/clone_map.rs:742:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/5750a6aa2777382bf421b726f234da23f990a953/library/core/src/panicking.rs:48:5
   3: creusot::clone_map::cloneable_name
   4: creusot::clone_map::CloneMap::to_clones
   5: creusot::translation::ty::translate_tydecl
   6: creusot::translation::ty::translate_ty_name
   7: creusot::translation::ty::translate_ty_inner
   8: creusot::translation::ty::field_ty
   9: creusot::translation::ty::translate_tydecl
  10: creusot::translation::ty::translate_ty_name
  11: creusot::translation::ty::translate_ty_inner
  12: creusot::translation::ty::field_ty
  13: creusot::translation::ty::translate_tydecl
  14: creusot::translation::ty::translate_ty_name
  15: creusot::translation::ty::translate_ty_inner
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  17: creusot::translation::ty::translate_ty_inner
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  20: creusot::util::signature_of
  21: creusot::translation::interface::interface_for
  22: creusot::ctx::TranslationCtx::translate_function
  23: creusot::ctx::TranslationCtx::translate
  24: creusot::translation::after_analysis
  25: rustc_interface::passes::QueryContext::enter
  26: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
  27: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  28: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  29: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

**Comment by jhaye** [comment]
The `DefKind` that triggers the panic in this case is `Union`.

**Comment by xldenis** [comment]
Ouch, I can fix this on Monday when I get back but the short of it is to avoid unions (even transitively) can you isolate the bug? (BTreeMap?)

**Comment by jhaye** [comment]
I think I have, I was using a crate called `smallstr` which relies on `smallvec` with the union feature enabled. I'm now working on replacing the type across the code base, which isn't too hard but will take a bit.

**Comment by xldenis** [comment]
Ok, this shouldn't be too tricky to fix, I'll try to handle it Monday.

**Comment by xldenis** [comment]
If you disable the `Union` feature it should work though.
