### ISSUE TITLE
Panic in still_specializable when impl source cannot be resolved

### ISSUE THREAD

**Issue by jhaye** [xldenis/creusot#603]
I have the following code:
```Rust
pub(crate) type MS = u32;

#[derive(Eq, PartialEq, Copy, Clone)]
pub struct MicroStep(MS);
```

It panics with
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', creusot/src/clone_map.rs:833:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/library/core/src/panicking.rs:48:5
   3: creusot::clone_map::CloneMap::to_clones
   4: creusot::translation::traits::<impl creusot::ctx::TranslationCtx>::translate_impl
   5: creusot::ctx::TranslationCtx::translate
   6: creusot::translation::after_analysis
   7: rustc_interface::passes::QueryContext::enter
   8: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
   9: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  10: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```
The trait derivations are the culprit.

**Comment by xldenis** [comment]
They're actually namespaced in `creusot_contracts::derive` and you need to import them explicitly or rustc will error about ambiguity.

The error you get here still shouldn't occur though.

**Comment by jhaye** [comment]
When using `creusot_contracts::derive` it does not crash.

**Comment by jhaye** [comment]
The following code triggers the same panic:

```rust
pub struct VecMap<K, V>
where
    K: Eq + Ord,
{
    v: Vec<(K, V)>,
}

impl<K: Ord + Eq, V> Default for VecMap<K, V> {
    fn default() -> Self {
        Self { v: Vec::new() }
    }
}
```

**Comment by xldenis** [comment]
So the problem is that `VecMap<K, V>` does not implement `creusot_contracts::Default`, the following code fixes the error:

```rust
impl<K: Ord + Eq, V> creusot_contracts::Default for VecMap<K, V>{
    #[predicate]
    fn is_default(self) -> bool { false }
}

impl<K: Ord + Eq, V> ::std::default::Default for VecMap<K, V> {
    fn default() -> Self {
        Self { v: Vec::new() }
    }
}
```

However, of course it shouldn't error in `still_specializable`. Instead `translate_impl` should check all the additional obligations that come from the `extern_spec`.
