### ISSUE TITLE
Compiler crashes at attempted to read from stolen value: rustc_middle::mir::Body

### ISSUE THREAD

**Issue by jhaye** [xldenis/creusot#616]
```
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', creusot/src/translation/function.rs:60:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/library/core/src/panicking.rs:142:14
   2: creusot::translation::function::translate_function
   3: creusot::ctx::TranslationCtx::translate
   4: creusot::translation::after_analysis
   5: rustc_interface::passes::QueryContext::enter
   6: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
   7: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
   8: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack

```

**Comment by xldenis** [comment]
Is this a `const` function like in #358 ?

**Comment by jhaye** [comment]
The error originates in a macro with a derive macro for `Hash` on a struct it is defining. When I remove the derive for `Hash` it does not crash any more.

**Comment by jhaye** [comment]
Specifically, it is the `Hash` derive right [here](https://github.com/lf-lang/reactor-rs/blob/main/src/ids.rs#L37) that is causing the crash.

**Comment by jhaye** [comment]
It also produces the same error [with the following modifications](https://gist.github.com/jhaye/0f1fbd8b2adc2b793477e9d75439563d#file-ids-rs-L29) when omitting `use creusot_contracts::derive::{Clone, PartialEq}` on the linked line. Note that all `Hash` derives are commented out. It seems then that in this instance the error originates in the standard derive of `PartialEq`.

**Comment by xldenis** [comment]
My guess is that those derives include a constant function somewhere inside which is known to break Creusot.

**Comment by jhjourdan** [comment]
I going to close this bug, because we do not have a repro case (the one listed above goes to a 404 error).
